### ISSUE TITLE
[BUG] soscleaner reveals previous hostname

### ISSUE THREAD

**Issue by slashdd** [soscleaner/soscleaner#105]
**Describe the bug**
previous hostname can be revealed in the soscleaner tarball under /var/log/*

**To Reproduce**
1. Have a machine originally called let's say 'lxd1'
2. Then change the hostname to 'lxd2'
3. Run sosreport
4. Run soscleaner against that generated sosreport

Depending on some factors such as:
- sosreport option used or not (--all-logs, ....) 
- system log rotation frequencies, ... and other factors. 
- ...

soscleaner can reveal fossil of previous hostname(s) because in my example, only lxd2 will be obfuscated but not former hostname lxd1.

Example:
```
May  8 20:35:09 lxd1 systemd[1]: Stopping D-Bus System Message Bus...
May  8 20:35:09 lxd1 systemd[1]: Stopping Regular background program processing obfuscateduser3...
May  8 20:35:09 lxd1 systemd[1]: Stopping Unattended Upgrades Shutdown...
May  8 20:35:09 lxd1 systemd[1]: apport.service: Failed to reset devices.obfuscateduser16: Operation not permitted
May  8 20:35:09 lxd1 systemd[1]: Stopping LSB: automatic crash report generation...
May  8 20:35:09 lxd1 blkdeactivate[322]: Deactivating block devices:
May  8 20:35:09 lxd1 systemd[1]: Stopping Deferred execution scheduler...
May  8 20:35:12 obfuscatedhost1 systemd-modules-load[54]: could not open moddep file '/lib/modules/5.0.1-050001-generic/modules.dep.obfuscateduser4'
May  8 20:35:12 obfuscatedhost1 systemd-modules-load[54]: Failed to lookup alias 'iscsi_tcp': Function not implemented
May  8 20:35:12 obfuscatedhost1 systemd-modules-load[54]: could not open moddep file '/lib/modules/5.0.1-050001-generic/modules.dep.obfuscateduser4'
May  8 20:35:12 obfuscatedhost1 systemd-modules-load[54]: Failed to lookup alias 'ib_iser': Function not implemented
```

**Expected behavior**
While I know this behaviour can be tricky to fix cause soscleaner doesn't keep an historic of previous hostname.

For the logs at least, maybe we could just make sure nothing in the hostname column is equal to the original sosreport and make sure it get obfuscated differently than the current hostname to differentiate them.

**Comment by jduncan-rva** [comment]
hmmmm.... yeah.  while certainly not desirable, it makes sense that it works that way. 
there's not a record of previous hostnames on a host (is there?) 
so until logs rotate off the old hostnames, it would have to be a known keyword. 

Can you think of a different way to handle it?

**Comment by slashdd** [comment]
I think the only place where old hostname(s) can be found would be inside logs.

Example:
Jul  8 20:27:18 **thinkpad** kernel: [    0.000000] Linux version 4.xx.0-xx-generic

Could we obfuscate the current hostname as usual, but for any other occurrence(s) of a old hostname (not equal to current hostname) in the same log column, just obfuscated it to **obfuscatedoldhost** ?

**Comment by slashdd** [comment]
hostname seems to always be found in the 4th columns (looking in syslog/kern.log) in Ubuntu at least.

**Comment by slashdd** [comment]
As @jduncan-rva log rotate will eventually make the old hostname disappear. Ideas are welcome, but for now I'll close this issue.
