### ISSUE TITLE
[BUG] Map sosreport with the right soscleaner tarball

### ISSUE THREAD

**Issue by slashdd** [soscleaner/soscleaner#128]
I can't seem to find a way to do the correlation between a given soscleaner tarball and it sosreport counterpart.

sosreport tarball: sosreport-thinkpad-20190703231836.tar.xz
soscleaner tarball: soscleaner-2323196989207201.tar.gz

Even looking the soscleaner log, there is no way to identify from which sosreport that socleaner originate.

Would be nice to have a correlation pattern such as keeping the same timestamp but dropping the hostname (if mentioned) in the tarball name.

```
sosreport tarball: sosreport-thinkpad-20190703231836.tar.xz
soscleaner tarball: soscleaner-20190703231836.tar.gz
```

So we can at least trace the origin base on similar timestamp, in case multiple sosreport are generated on the same machine.

or maybe another csv report ? doing the mapping just like it does for user, hostname, ...

```
$ cat soscleaner-2323196989207201-sosreport.csv 
Original sosreport,Obfuscated sosreport
sosreport-thinkpad-20190703231836.tar.xz, soscleaner-2323196989207201.tar.gz
```

**Comment by slashdd** [comment]
I opted for creating a new report in order to map the sosreport to its soscleaner counterpart.

Here's where I'm at the moment. The only item missing is how to get the sosreport filename from which soscleaner run against. I couldn't find a efficient way yet even after looking under sos_log, sos_report and else to clearly get the sosreport tarball name.

@jduncan-rva, If you can think of anything let me know. Otherwise, I'll continue to look at it later when I get back from vacation.

```
--- /usr/lib/python2.7/dist-packages/soscleaner.py.ORIG	2019-07-04 13:30:48.558233659 +0000
+++ /usr/lib/python2.7/dist-packages/soscleaner.py	2019-07-04 14:43:58.313142132 +0000
@@ -580,6 +580,14 @@
             self.logger.exception(e)
             raise Exception('CREATE_USERNAME_REPORT_ERROR: Unable to create report - %s', un_report_name)
 
+    def _create_sos_report(self):
+            sos_report_name = os.path.join(self.report_dir, "%s-sosreport.csv" % self.session)
+            self.logger.con_out('Creating sosreport Report - %s', sos_report_name)
+            sos_report = open(sos_report_name, 'w')
+            sos_report.write('Original Sosreport,Obfuscated Sosreport\n')
+            sos_report.write('%s\n' % self.session)
+            self.logger.info('Completed sosreport Report')
+
     def _create_hn_report(self):
         """Creates a report of hostnames and their obfuscated counterparts"""
         try:
@@ -651,6 +659,7 @@
         self._create_un_report()  # pragma: no cover
         self._create_mac_report()  # pragma: no cover
         self._create_kw_report()  # pragma: no cover
+        self._create_sos_report()  # pragma: no cover
         # os.chmod(self.logfile, 0o600)
```

**Comment by jduncan-rva** [comment]
this would also fall down if you're running data sets that aren't sosreports. There are several places where that logic is parsed. 

Only thing that springs to mind is to look at the basename for the tarball or uncompressed directory  when its being uncompressed. We could probably add a step to `extract_sosreport`. Maybe? This would also isolate it from non-sosreport workflows.

I agree that we need to make it cleaner. I'll mull this over during the US holiday.

**Comment by slashdd** [comment]
Yep that did the trick.
