### ISSUE TITLE
[RFE] soscleaner report_dir reconsideration

### ISSUE THREAD

**Issue by slashdd** [soscleaner/soscleaner#135]
While soscleaner save everything in /tmp (which I don't disagree), I see downside of it, for let's say user having frequent reboot (crash) or simply a maintenance and system needs a reboot during an investigation made by a third party.

After the reboot, it will accidentally remove all the soscleaner dir and if third party request something based on the obfuscated<DATA><COUNT> then the user won't be able to do the correlation anymore and would need to start the collection over again. Especially now with the user ids randomisation which will force obfuscateduser to not remain persistent across soscleaner run. 

Would it be a good idea to consider /var/tmp ? and save soscleaner file under /var/tmp/<self.session>/ pattern ?

Example:
`/var/tmp/soscleaner-1808936689191598`

One folder per soscleaner run, containing the soscleaner files:

```
soscleaner-1808936689191598-dn.csv       
soscleaner-1808936689191598-ip.csv  soscleaner-1808936689191598-mac.csv        
soscleaner-1808936689191598-username.csv  
soscleaner-1808936689191598.tar.gz
soscleaner-1808936689191598-hostname.csv  
soscleaner-1808936689191598-kw.csv  
soscleaner-1808936689191598.log
```

**Comment by slashdd** [comment]
On the other end, one would need sufficient storage space on /var/tmp, and remember to delete the soscleaner files when no longer needed, otherwise they will remain there.

**Comment by slashdd** [comment]
Or we leave it as is under /tmp and offer a --backup parameter to copy the content elsewhere ?
So one could run let's say `soscleaner --backup /var/tmp` before performing the reboot in order to keep the soscleaner files.

**Comment by slashdd** [comment]
I'm thinking out loud here, but the fact that soscleaner files can be accidentally lost after a reboot make me concern about it.

**Comment by jduncan-rva** [comment]
`self.report_dir = '/tmp'` is just the default location. 

It can be modified on the CLI using the `-o` option. 

```
parser.add_option("-o", "--output-dir", action="store", default="/tmp", dest="report_dir",
                            help="Directory to store soscleaner obfuscated sosreport or dataset",
                            metavar="DIRECTORY")
```

Is that sufficient?

**Comment by jduncan-rva** [comment]
Feel free to re-open this if above is insufficient. Closing this for now to scope out the next minor release
