### ISSUE TITLE
[RFE] update 'last' file location

### ISSUE THREAD

**Issue by bmr-cymru** [soscleaner/soscleaner#161]
Since additional data collection relating to user logins have been added to `sos` the `last` command has been moved from its own plugin to a new `login` plugin. This means that the location of the `last` file used by soscleaner has changed.

As well as `"sos_commands/last/lastlog_-u_1000-60000"` soscleaner should now also check for `sos_commands/login/lastlog_-u_1000-60000`.

This change will be included in the next release of `sos`.

**Comment by slashdd** [comment]
Done 
https://github.com/soscleaner/soscleaner/blob/master/soscleaner/soscleaner.py#L97

**Comment by bmr-cymru** [comment]
That still looks like the original to me:

```python
        # obfuscating users from the last command, per rfe #79
        self.users_file = 'sos_commands/last/lastlog_-u_1000-60000'
        self.user_db = dict()
        self.user_count = 0
```

It needs to test to see if the original location (`sos_commands/last/...`) exists, and if not then use the new one (`sos_commands/login/...`).
