### ISSUE TITLE
[BUG] cleaner includes the log file in tar

### ISSUE THREAD

**Issue by skhobbs18** [soscleaner/soscleaner#168]
**Describe the bug**
When running soscleaner against a sosreport, the soscleaner.log file is repackaged in the tar file which is sent to support teams.  This log file includes the remapping back to all obfuscated fields.  This defeats the purpose of the clean to begin with.

**To Reproduce**
1. generate sosreport
2. run soscleaner against sosreport
3. untar the soscleaner
4. view log file

**Expected behavior**
The soscleaner result which is sent to the vendor for support should not have any confidential data.

**Comment by jduncan-rva** [comment]
this is a regression. it used to be excluded. will investigate, but I don't have a ton of cycles right now. Would anyone like to take this on?

**Comment by arif-ali** [comment]
@skhobbs18 I have just tried to reproduce on a test system, I can't see the soscleaner log in the resulting tarball. Could you expand, and possible reproduce this on a fresh system.

**Comment by slashdd** [comment]
I confirmed :

```
ls -altr

total 2412
-rw-r--r--  1 root root    4575 Apr 17 02:23 soscleaner-2857542954687304.log
-rw-------  1 root root 2447402 Apr 17 02:23 soscleaner-2857542954687304.tar.gz
drwx------  4 root root    4096 Apr 17 02:27 ..
drwxr-xr-x 12 root root    4096 Apr 17 02:27 soscleaner-2857542954687304
drwxr-xr-x  3 root root    4096 Apr 17 02:27 .
```

**Comment by slashdd** [comment]
Most likely a regression cause by e9963799cb7eb10ee8be73f13999269572d1c350

**Comment by arif-ali** [comment]
> I confirmed :
> 
> ```
> ls -altr
> 
> total 2412
> -rw-r--r--  1 root root    4575 Apr 17 02:23 soscleaner-2857542954687304.log
> -rw-------  1 root root 2447402 Apr 17 02:23 soscleaner-2857542954687304.tar.gz
> drwx------  4 root root    4096 Apr 17 02:27 ..
> drwxr-xr-x 12 root root    4096 Apr 17 02:27 soscleaner-2857542954687304
> drwxr-xr-x  3 root root    4096 Apr 17 02:27 .
> ```

That's not in the tar file, right?

**Comment by skhobbs18** [comment]
I confirmed this with my customers data.  They provided a cleaned sosreport this week.

$ grep soscleaner host4-2020-Apr-15-16\:57\:48/installed-rpms 
soscleaner-0.4.4-2.el7.noarch                               Fri Oct  4 15:12:20 2019

$ ll
total 72
drwxrwxr-x.  2 shobbs shobbs    91 Apr 16 09:54 archive
drwxrwxr-x. 14 shobbs shobbs  4096 Apr 16 09:54 host4-2020-Apr-15-16:57:48
-rw-r--r--.  1 shobbs shobbs 66291 Apr 15 18:06 soscleaner-3362796278160026.log
drwxrwxr-x.  2 shobbs shobbs    28 Apr 16 09:54 work

**Comment by arif-ali** [comment]
okie, confirmed
