### ISSUE TITLE
[BUG] soscleaner can't locate users_file due to sosreport change

### ISSUE THREAD

**Issue by slashdd** [soscleaner/soscleaner#174]
Starting with sosreport (version 3.9)

soscleaner no longer locate the users_file:
`Unable to locate user file - /tmp/soscleaner-6973146288353025/soscleaner-6973146288353025/sos_commands/last/lastlog_-u_1000-60000`

sosreport move the lastlog commands from last.py to login.py

sosreport:
https://github.com/sosreport/sos/blob/master/sos/report/plugins/login.py#L26

soscleaner:
https://github.com/soscleaner/soscleaner/blob/master/soscleaner/soscleaner.py#L100

**Comment by jduncan-rva** [comment]
Hey folks. 

I've historically been the maintainer for RHEL/CentOS/Fedora. 

I've tried to find time for soscleaner, and simply haven't been able to. Every time I get ready to work on $(some_problem), life or my day job pop up and I have to set it back down. Apologies. 

I may have time in the future, but as for right now, I don't have cycles to give to the project. If someone wants to step up in the Fedora/RHEL/CentOS ecosystem it would be pretty awesome.

-jduncan
