### ISSUE TITLE
filter IPv6 addresses

### ISSUE THREAD

**Issue by jduncan-rva** [soscleaner/soscleaner#7]

**Comment by jduncan-rva** [comment]
this will likely land in 0.4.0

**Comment by jduncan-rva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [obfuscate IPv6 addresses](https://trello.com/c/1fE6qeJl/13-obfuscate-ipv6-addresses)

**Comment by jduncan-rva** [comment]
I'm going to slip this to 0.4.1 for time/level of effort

**Comment by ansvu** [comment]
Hello, 
Do we have any updates on soscleaner to support ipv6? Thanks in advance.

**Comment by jduncan-rva** [comment]
soscleaner isn't actively developed at this point. The functionality was merged into the sos project at https://github.com/sosreport/sos.

**Comment by ansvu** [comment]
Thanks, jduncan-rva.
